version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:admin123@db:5432/nest_prisma_firebase # Aqui usamos "db" como hostname
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: nestjs-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=nest_prisma_firebase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
